site_name: Null AI Documentation
theme:
  name: material
  palette:
    - scheme: slate
      primary: red
      accent: green
  logo: assets/logo.png
extra_css:
  - stylesheets/extra.css
nav:
  - Overview: index.md
  - Support pokemon: support-pokemon.md
  - Switch AI: switch-ai.md
  - Move scoring: move-scoring.md
  - Q&A: qa.md
site_url: https://jellytronical.github.io/Null-AI-Documentation/