site_name: Pokemon Null AI Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: slate
      primary: red
      accent: green
  logo: assets/logo.png
extra_css:
  - stylesheets/extra.css
nav:
  - Overview: index.md
  - Switch AI: switch-ai.md
  - Scoring: move-scoring.md
  - Move scoring reference: move-scoring-reference.md
  - Support pokemon: support-pokemon.md
  - FAQ: faq.md
site_url: https://jellytronical.github.io/Null-AI-Documentation/
markdown_extensions:
  - admonition
  