site_name: Null AI Docs prototype
theme:
  name: material
  palette:
    - scheme: slate
      primary: red
      accent: green
  logo: assets/logo.png
extra_css:
  - stylesheets/extra.css
nav:
  - Null AI Overview: index.md
  - Support pokemon: Support pokemon.md
  - Switch AI: Switch AI.md
  - Move scoring: Move scoring.md
  - Q&A: QA.md
site_name: Null AI Documentation
site_url: https://jellytronical.github.io/Null-AI-Documentation/